export default function ServiceCard({ icon, title, description }) {
  return (
    <div
      className="
        h-full
        bg-white
        rounded-xl
        p-5
        sm:p-6
        md:p-8
        border
        border-[#E6D8C3]
        flex
        flex-col
        transition-all
        duration-300
        hover:-translate-y-1
        hover:shadow-lg
      "
    >
      <div
        className="
          text-[#2f5233]
          mb-1
        "
      >
        {icon}
      </div>

      <h3
        className="
          text-lg
          sm:text-xl
          md:text-2xl
          font-bold
          mt-4
          sm:mt-5
          text-[#4a2e1e]
          leading-tight
        "
      >
        {title}
      </h3>

      <p
        className="
          mt-3
          sm:mt-4
          text-sm
          sm:text-base
          text-gray-600
          leading-6
          flex-grow
        "
      >
        {description}
      </p>
    </div>
  );
}
